#!/bin/bash
set -e

go get github.com/vito/gosub

if [ ! $(which gosub) ]; then
    echo "Gosub required to update dependencies in bosh/*/spec files."
    echo 'Please install with `go get github.com/vito/gosub`'
    exit 1
fi

loggregator_root=${GOPATH}

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'
      gosub list "$@" | \
        sed -e 's|\(.*\)|\1/*.go # gosub|g' | \
        while read line; do
          if ! [[ "$line" == *"loggregator-bench"* ]]; then
            echo "- loggregator-release/src/$line"
          else
            echo "- $line"
          fi
        done
    } > spec.new

    mv spec.new spec
  )
}

sync_package doppler -test code.cloudfoundry.org/loggregator-bench/doppler &

wait

